### ISSUE TITLE
Update pandoc-api-version for Pandoc 2

### ISSUE THREAD

**Issue by iandol** [htdebeer/paru#23] opened 2017-09-05 04:38 UTC
Pandoc 2 should be getting close to release ([there is one outstanding issue, and documentation to finish](https://github.com/jgm/pandoc/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22pandoc+2.0%22)). 

[pandoc-types has been upgraded to 1.17.1](http://hackage.haskell.org/package/pandoc-types-1.17.1) — and thus paru seems currently broken with the latest Pandoc 2 nightlies:

```console
👉  pandocomatic -b 'Lu.md'
pandoc	--standalone \
	--filter=/Users/ian/.pandoc/filters/removeHR \
	--filter=/Users/ian/.pandoc/filters/authorRemoveHash \
	--bibliography=/Users/ian/.pandoc/Core.json \
	--csl=/Users/ian/.pandoc/csl/neuron.csl \
	--from=markdown \
	--to=docx \
	--reference-doc=/Users/ian/.pandoc/templates/custom.docx \
	--dpi=300 \
	--output=./Lu.docx
Error running filter /Users/ian/.pandoc/filters/removeHR:
Error in $['pandoc-api-version'][3]: expected Int, encountered Null
Pandocomatic needed 1.2 seconds to convert 'Lu.md'.
```
I tried to find how this works, but can't see why this bug is triggering (how is `pandoc-api-version` generated?).

```console
👉  pandoc --version
pandoc 2.0
Compiled with pandoc-types 1.17.1, texmath 0.9.4.1, skylighting 0.3.3
Default user data directory: /Users/ian/.pandoc
Copyright (C) 2006-2017 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by talazem** [comment] 2017-09-05 23:58
I am getting the same error, but only when running the filters removeHR and authorRemoveHash to output as docx and HTML. The same filters when outputting as LaTeX does not produce this error.

**Comment by iandol** [comment] 2017-09-06 02:31
OK, I've found where this lives: https://github.com/htdebeer/paru/blob/master/lib/paru/filter/document.rb#L39 and I assumed the error is probably triggered when checking this on line 74. 

I just tested in IRB, but it works there:

```bash
irb(main):001:0> x = [1, 17, 0, 5]
=> [1, 17, 0, 5]
irb(main):002:0> x <=> [1,17,1]
=> -1
```

Ah, but the version class does specify 4 values here, so this is where the error triggers:

https://github.com/htdebeer/paru/blob/master/lib/paru/filter/version.rb

**Comment by htdebeer** [comment] 2017-09-06 08:49
Propagating the error to pandocomatic is a good idea. I'll create an issue for that in pandocomatic's repository.

**Comment by htdebeer** [comment] 2017-09-06 09:32
I checked in the fix for the version check and released a new version.

**Comment by htdebeer** [comment] 2017-09-06 09:47
I created a new branch, "paru-for-pandoc2", for development of a pandoc2 compatible paru library: see https://github.com/htdebeer/paru/tree/paru-for-pandoc2

If I run the test with pandoc2, 10 of 44 tests break. Most likely due to differences in generated output and some small filter changes. These are things to check out.

It would be nice to have paru be pandoc version agnostic. Otherwise we will have to keep maintaining two separate version for a while after the release of pandoc2. I suppose people using stable Linux distributions will be on pandoc1 by default for a while. 

Ideas welcome.

**Comment by htdebeer** [comment] 2017-09-06 11:01
- I've made all tests green with pandoc2 in the new pandoc2-compat branch. The odd thing is, only the generated output needed to be updated for that. This means that the changes to pandoc-types are not yet covered by the tests (or not that big of a change?)
- I've created the first pandoc2 compatible release: paru-0.3.0a. Testing is appreciated.

**Closed by htdebeer** 2017-09-06 11:01 UTC
Labels: pandoc2compatibility

**Comment by iandol** [comment] 2017-09-06 11:19
Great Huub! I think that the big AST changes are not always going to coincide with a major pandoc version change. This is a problem in the sense that Perhaps Pandoc V2.01 includes a V1.2 pandoc-types which is where the major changes for paru would occur. Therefore a mechanism to handle this has to dissociate the Pandoc changes (command line options etc), with AST changes as specified by the pandoc-types api. 

[Potential AST changes are labelled as such in the pandoc repo](https://github.com/jgm/pandoc/issues?utf8=%E2%9C%93&q=is%3Aopen%20is%3Aissue%20label%3A%22AST%20change%22%20), so that is where we should look. And of course the pandoc-types changelog. There is a pandoc-types-1.19 with this changelog, basically adding a pagebreak element then reverting it :-) 

http://hackage.haskell.org/package/pandoc-types-1.19/changelog 

There are some things which are not labelled as AST change, for example [this epic thread](https://github.com/jgm/pandoc/issues/168) on new div syntax which is only tagged as a reader issue, which possibly just tap into existing div attribute support? 

Perhaps we should make two issues we leave open, one that tracks potential command line changes and another tracking potential AST changes?

**Comment by htdebeer** [comment] 2017-09-06 12:00
That's possible. But these type of threads might get a bit difficult to read after a couple of months/years. Maybe we can create two labels instead, and create issues for each change and label them appropriately?

Anyway, I do not think these changes happen that often, so whatever way we start administrating them will probably be fine.

And that probably also means that it should be possible to create one branch that combines both pandoc 1 and pandoc 2. We only need a way to annotate what feature is supported by what version of pandoc / pandoc-types. And maybe a list of paru versions mapped to suitable pandoc versions for the truly breaking API changes.

**Comment by htdebeer** [comment] 2017-09-06 13:56
As for propagating pandoc errors to pandocomatic. Do you have a simple reproducible scenario where pandoc exits in error? 

Just supplying a non existing file to the `--bibliography` option does not do the trick. Or rather, then the error about not being able to find that file is already propagated. Do you have an example where the error isn't propagated?

**Comment by iandol** [comment] 2017-09-06 14:37
Labels is a much better idea +1

Well THIS bug you just fixed was one case, the paru filter error'ed out and so did Pandoc (I got return value 83 when I tested it) 😸  So a broken filter should work :-)

**Comment by htdebeer** [comment] 2017-09-06 18:07
But that one has been fixed. I created the following crashing filter instead:

```
#!/usr/bin/env ruby
require "paru/filter"

Paru::Filter.run do 
    with "Emph" do |e|
        e.append(Paru::PandocFilter::Para.new([]))
    end
end
```

But when I run it through pandocomatic on a test file, it outputs:

```
pandoc: Error in $.blocks[0].c[6].c[1]: failed to parse field blocks: failed to parse field c: failed to parse field c: mempty
Pandocomatic needed 0.2 seconds to convert 'test.md'.
```

It looks like it already is outputting errors from pandoc, although that is not registered by pandocomatic. At least I now have an example to work with trying to capture and handle the error.

**Comment by htdebeer** [comment] 2017-09-06 19:54
Added improved error handling to paru when pandoc fails. Next step is to integrate it in pandocomatic.

**Comment by iandol** [comment] 2017-09-07 00:53
I've lightly tested paru-0.3.0b (filtering) and everything seems to be working...
